### ISSUE TITLE
Variant on Result::unwrap with original error thrown

### ISSUE THREAD

**Issue by brigand** [alexsasharegan/safe-types#3]
With `Result.Err(myError).unwrap()`, the error gets wrapped in a plain Error instance, which is then thrown. Could a method be added for doing the following?

```js
result.match({
  Ok: (value) => value,
  Err: (err) => {
    throw err;
  },
});
```

It enables things like `map_err` to be used efficiently in validation code, where custom error types are often needed, and throwing errors is common.

Simple name: `unwrap_or_throw`, or a shorter name: `try`. The name "try" comes from the core rust macro of the same name.

```rust
fn incr_string(num_str: String) -> Result<String, ParseIntError> {
  let num: u64 = try!(num_str.parse());
  let num = num + 1;
  Ok(format!("{}", num))
}
```

The reason throwing is common is the lack of any clean way to do early returns in JS, so while it doesn't fit into this library as an ideal, I think it's very useful as a practical tool.

**Comment by alexsasharegan** [comment]
The thing I always find hard about this is the total lack of type support for thrown values. That's why I implemented the unwrap method to throw a standard `Error` instance.

That said, this seems like a good idea. Even though this whole library is at least 50% clone of rust, I'm concerned the `result.try()` syntax might be confusing. Do you think `must` and `must_err` would be any clearer? They would unwrap or throw the original values for their respective cases.

**Comment by alexsasharegan** [comment]
The `try` name seems more appropriate for it's error throwing semantics though. Maybe the name is fine as is. I can always properly explain in a doc block.

**Comment by alexsasharegan** [comment]
Out in 4.17.0

https://github.com/alexsasharegan/safe-types/blob/master/CHANGELOG.md

**Comment by alexsasharegan** [comment]
By the way, in practice, this is really handy. Good addition!
